add hub-dashboard as a poster
reichlab/decisions pull request #3
Opened 2024-12-12 23:14 UTC by zkamvar

2024-12-13 16:39 UTC, elray1 requested changes
Thanks for putting this together!

2024-12-13 16:39 UTC, elray1 commented on project-posters/hub-dashboard.md
> +- Web app with server-side logic to render tables and/or figures, e.g. using Shiny or Streamlit
```suggestion
There are two pieces to the dashboard:

1. Creation of score data
2. The website itself

For score data, we will write functionality in R to compute scores after the close of each modeling round when target data become available and cache the scores for later retrieval by the process that's used to create the web app.

- We will use R to compute scores because there is existing functionality for score computation in the hubverse in the hubEvals package
- Saving score data:
    - S3 bucket
    - github pages branch of the github repo used for the dashboard
    - Another branch on a github repo used for the dashboard

The interactive website:
- R markdown document, quarto document, or similar that pre-computes all tables/figures used to display scores.
- Javascript app running in client side browser fetches data as needed and generates plots/etc. This is similar to predtimechart.
- Web app with server-side logic to render tables and/or figures, e.g. using Shiny or Streamlit
- webR or webpy runs R or python in the browser to dynamically create figures and tables
```

2024-12-13 19:15 UTC, zkamvar commented on project-posters/hub-dashboard.md
> +We are _not_ trying to make a generalizable dashboard that can accomodate all
mm I see

2024-12-13 19:18 UTC, zkamvar commented on project-posters/hub-dashboard.md
> +2. predtimechart vis,
oh gotcha. I had actually missed that point 😳

2024-12-13 19:18 UTC, zkamvar commented on project-posters/hub-dashboard.md
> + - Docker container
Yes, we can.

2024-12-13 19:21 UTC, zkamvar commented on project-posters/hub-dashboard.md
> + - orchestration: (example) the r-universe is an opt-in process that requires little to no effort from package maintainers
Sure! I'll comment briefly here and expand in a subsequent commit.

We do not use the R-universe in this process, but we use its framework as an example of how this can work.

2024-12-13 20:02 UTC, zkamvar commented on project-posters/hub-dashboard.md
> + - does not require knowledge of anything more than Markdown or YAML
## Executive Summary

I think that's a fair assessment, and the discussion is a bit broader scope than this particular project. The app and the distributed workflows are not mutually exclusive options. The way we currently operate still requires a fair bit of effort. The app was designed as a kind of stretch goal to satisfy the fact that the CDC folks did not have the capacity to maintain yet another site.

## Broader Description

My take on this is that providing a standard set of GitHub actions still requires maintenance on our part and it really depends on the service level hub admins will expect from the core developers. 

There are a few models that exist for this, each with decreasing technical expertise required for users: 

1. GitHub actions or [reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) and require admins to build their own workflows.
2. GitHub workflows and require admins to be aware of updates and update accordingly.
3. GitHub workflows and provide help to admins who need it. 
4. GitHub app that triggers centralized workflow. 

For example, [r-lib/actions](https://github.com/r-lib/actions) is primarily strategy 1 and secondarily strategy 2. 

Our current strategy with the hubs is pretty firmly in strategy 3, but not everyone gets the message to update (think about how many emails you and Nick must field per day) which causes problems that require extra effort on everyone's part (e.g. [the recent ubuntu kerfuffle](https://groups.io/g/hubverse/topic/github_actions_workflow/110067076) leading to https://github.com/cdcepi/FluSight-forecast-hub/pull/1251). I've had plenty of experience with this strategy and I find it even more taxing than any of the other strategies because it's so hard to make sure that everyone is up-to-date. I actually continue to get notifications from The Carpentries that workflows have failed because I was the last one to update them. 

I still haven't been able to describe it well enough, but the way I am envisioning the hub dashboard orchestration working is that an app and a workflow are not mutually exclusive. If we provide re-usable workflows (strategy 1) AND provide example workflows (strategy 2), then hub admins who are comfortable with GitHub workflows can use those to build their dashboard websites. 

However, given the desire to not require yet another set of workflows to maintain, the app can be an optional step in to fill that role (as long as we label that as beta).

2024-12-14 02:42 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +### What are we doing?
This section, with the named focus on predtimechart and step-ahead quantile predictions, feels too narrow. E.g., the variant nowcast hub found the functionality useful without using predtimechart or having step ahead quantile predictions. Could we frame this slightly more broadly but still keep those as key use cases?

2024-12-14 02:47 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +### What are we doing?
Like, I see this initial push as having developed two separate things:
1. a theme-able and low-maintenance website with customizable static content
2. optional integrations with interactive/dashboard javascript apps like predtimechart (for hubs with step-ahead quantile outputs) and the eval dashboard (coming soon)

And maybe we can/should separate those pieces of functionality more specifically. Unless we really only envision hubs using this if they are planning on using pretimechart and predeval (the name I just made up).

2024-12-14 02:49 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +We are _not_ trying to make a generalizable dashboard that can accommodate all
I feel like the current hub dashboard basic functionality DOES support all sites, but certain integrations (like predtimechart) are only available for certain hubs, or with additional customization

2024-12-14 02:52 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> + - display an evaluation report of model outcomes from the same specified hub
Once again, I want to suggest that these more advanced integrations not be listed as primary deliverables, but serve as "optional" integrations that are part of hubdashboard functionality but not assumed to be active in every hub that has a dashboard.

2024-12-14 02:53 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +3. evaluations dashboard, and
Just flagging additional places where I think we could indicate viz and eval components as optional, not central, integrations.

2024-12-14 02:54 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +4. the orchestration of these tools for continuous deployment
Could we be more specific here about deployment being something that is desired both perhaps on a schedule and on-demand. I think this is a requirement for the dashboards to be usable by hub admins.

2024-12-14 02:56 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### 3. evaluations dashboard
I suggest simply pointing to the eval project poster here rather than having a second place where this content can live and get stale.

2024-12-14 02:57 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### 2. predtimechart vis
Could we leave this section as a more general viz app integration, with predtimechart as one option, and some reasons why it is a good choice?

2024-12-14 03:00 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> + - docker can provide an abstraction for any static site generator we want
are there other existing public docker containers that have static site generators (not ours) that could be used? or is what we want custom enough that we want/need our own?

2024-12-14 03:10 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### Evaluations
again, could we link to the eval docs here?

2024-12-16 15:14 UTC, bsweger commented on project-posters/hub-dashboard/hub-dashboard.md
> + - be built on demand
I'm curious about where this requirement comes from, because prior discussions that I remember focused on the need to update a dashboard only upon round close.

2024-12-16 15:25 UTC, nickreich commented on project-posters/hub-dashboard/hub-dashboard.md
> + - be built on demand
```suggestion
 - be built on demand for use cases such as data needing to be updated not on a schedule (see early season issues with Flusight in fall 2024)
```

2024-12-20 21:49 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> + - be built on demand
This came from the fact that corrections happen and ensembles builds are necessarily submitted after round close.

2024-12-20 21:50 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +### What are we doing?
fixed in 728b3e7

2024-12-20 22:01 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### 3. evaluations dashboard
😅 that's in another PR.

2024-12-20 22:01 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### 3. evaluations dashboard
That being said, once that PR is merged, I'll go back and link here.

2024-12-20 22:08 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> + - docker can provide an abstraction for any static site generator we want
The issue is less the choice of docker container than the structure of the repository (the point above: "all static site generator templates are complex in some way").

Nearly all static site generators assume that you are going to build your own special little site that you will lovingly hand-craft and infuse with your oh-so-unique essence of your brilliance. This is why you end up with the "do not touch unless you know what you are doing" folders of `static/` `assets/`, `templates/`, `scripts/` and some sort of tortuous config file written in deeply nested YAML or TOML. 

By providing a docker image, we can abstract the templating mess and allow the hub admins to just focus on being able to throw some markdown files in a template, specify the order they should appear, and get a website.

2024-12-20 22:11 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +```
I'm honestly not sure the best way to do this either. I want to indicate that GitHub is issuing the request to fetch the repository.

2024-12-20 22:13 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +We are _not_ trying to make a generalizable dashboard that can accommodate all
addressed in [728b3e7](https://github.com/reichlab/decisions/pull/3/commits/728b3e7d0fb9bc8b269baff09abad089dbdfec85)

2024-12-20 22:13 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> + - display an evaluation report of model outcomes from the same specified hub
addressed in [728b3e7](https://github.com/reichlab/decisions/pull/3/commits/728b3e7d0fb9bc8b269baff09abad089dbdfec85)

2024-12-20 22:13 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +3. evaluations dashboard, and
addressed in [728b3e7](https://github.com/reichlab/decisions/pull/3/commits/728b3e7d0fb9bc8b269baff09abad089dbdfec85)

2024-12-20 22:13 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +4. the orchestration of these tools for continuous deployment
addressed in [728b3e7](https://github.com/reichlab/decisions/pull/3/commits/728b3e7d0fb9bc8b269baff09abad089dbdfec85)

2024-12-20 22:14 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> +#### 2. predtimechart vis
addressed in [662efa4](https://github.com/reichlab/decisions/pull/3/commits/662efa4ab0252502165777bd4bb5d31f38c9b408)

2024-12-20 22:14 UTC, zkamvar commented on project-posters/hub-dashboard/hub-dashboard.md
> + - be built on demand
clarified in [d0d5f06](https://github.com/reichlab/decisions/pull/3/commits/d0d5f06523dab463a4564490ce657733f81f654e)

2024-12-23 15:36 UTC, elray1 reviewed
My remaining "big question" about this project that's not mentioned in this poster is what level of support we're going to give to people who want to create static content using R, a la variant nowcast hub.  I haven't actually kept up with the process that's being used there, but I believe the process has been to manually add any .js that's needed, and manually render Rmd --> md or html to create new pages?  Is this a viable/generalizable plan? Do we plan to formalize support for people who want to do this kind of thing?  I feel like a statement about this should either go under the goals or the anti-goals.

2024-12-24 19:18 UTC, zkamvar commented
> My remaining "big question" about this project that's not mentioned in this poster is what level of support we're going to give to people who want to create static content using R, a la variant nowcast hub. I haven't actually kept up with the process that's being used there, but I believe the process has been to manually add any .js that's needed, and manually render Rmd --> md or html to create new pages? Is this a viable/generalizable plan? Do we plan to formalize support for people who want to do this kind of thing? I feel like a statement about this should either go under the goals or the anti-goals.

It's definitely an anti-aim to provide specific support for anything that might come up with relation to user-generated content and I will add that in the document. 

The reason why it's an anti-aim has to do with the myriad of options that come up when you want to translate a folder of Markdown documents into an HTML website. This is why I wanted to use an existing generator instead of rolling our own. 

We specify the structure of the website, the pages we can compute, the underlying website generator, and some examples for customization. Beyond that, the customization is entirely handled by the generator (quarto) and anything else is off-label usage. If people want support for the customization, quarto has plenty of documentation that can be perused.

2025-01-06 15:23 UTC, elray1 approved these changes

2025-01-07 22:38 UTC, merged