[RFC] hub dashboard orchestration
reichlab/decisions pull request #5
Opened 2024-12-14 00:06 UTC by zkamvar

This is still a draft, but it's most of the way there.

This is dependent on #3 and effectively is an RFC for a decision that was
already made and implemented, but it would be good to have a discussion around
this since there is still some uncertainty.

2024-12-16 14:13 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> + - A set of GitHub workflows only
I've been wondering what other options might be available.  Here are a few thoughts, I'm not sure how viable any of them are.

- Would it be possible to use a github app to manage permissions to enable pushing workflow updates to hub dashboard repos (and/or hub repos)?
- Could we use reusable workflows more heavily, so that in each hub dashboard repo (or hub repo) there is only a small/minimal workflow that will need minimal updating, and which calls a single reusable workflow that is maintained centrally in 1 place in the hubverse? The idea is that this would make there be less "surface area" for failure in workflows in hub or hub dashboard repos, so that they are less likely to need updates.
- Could we use Docker in workflows to get a more stable run environment?  Again, with the goal of reducing the frequency with which we need to make updates.

There may be other ideas as well!

2024-12-16 14:14 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +### Other Options Considered
I've been wondering what other options might be available.  Here are a few thoughts, I'm not sure how viable any of them are.

- Would it be possible to use a github app to manage permissions to enable pushing workflow updates to hub dashboard repos (and/or hub repos)?
- Could we use reusable workflows more heavily, so that in each hub dashboard repo (or hub repo) there is only a small/minimal workflow that will need minimal updating, and which calls a single reusable workflow that is maintained centrally in 1 place in the hubverse? The idea is that this would make there be less "surface area" for failure in workflows in hub or hub dashboard repos, so that they are less likely to need updates.
- Could we use Docker in workflows to get a more stable run environment?  Again, with the goal of reducing the frequency with which we need to make updates.

There may be other ideas as well!

2024-12-16 14:19 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +# 2024-12-13 Orchestration of the Dashboard Build Process
Although it's valuable to think this through in the specific context of the dashboard build process, I've been wondering if it would (or would not) be helpful to expand the scope of discussion here a bit to the general problem of workflow management in the hubverse.  For example, Zhian and Anna were scrambling a bit last week to get workflow updates for validations out to hubs, when the `ubuntu-latest` runner changed the major OS version.  We also have several other actions used for other purposes.  It seems like it would be nice to arrive at a general solution.

2024-12-17 16:48 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +# 2024-12-13 Orchestration of the Dashboard Build Process
For posterity, repeating my zoom comments here.

I agree that the multitude of workflows is a challenge to tackle, but we should focus on solving that problem in the context of the hub dashboard project. If we arrive at a solution that's generalizable to the hubverse as a whole, we can start a new stream of work to implement it on a wider scale.

2024-12-17 17:24 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +   - **Not chosen because of maintenance burden for hubverse admins** (see
> We will host the App's webhook code on a free service like glitch.io

Assuming that decision not to rely solely on GitHub workflows is related to the quoted text from the above list of decisions...

I'm still unclear on why we need to host webhook code on Glitch, etc. instead of having a manually-triggered action in the hub-specific repos (e.g., [variant-nowcast-hub-dashboard](https://github.com/reichlab/variant-nowcast-hub-dashboard)) that use the GitHub api to trigger a [workflow](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event)/[repository](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event) dispatch event in the [central dashboard "control room"](https://github.com/hubverse-org/hub-dashboard-control-room/tree/main/.github/workflows)

Is there a technical and/or code-reuse reason we haven't tried on-demand updates w/o writing our own intervening API?

If not, it's appealing to remove the extra moving part (i.e., Glitch/server). Asking hub admins to manually run a GitHub workflow to update the dashboard doesn't seem overly-burdensome, especially for a first iteration of dashboards.

2024-12-17 17:32 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +   - **Not chosen because of maintenance burden for hubverse admins** (see
Adding that I also saw this note above:

> The admins of at least one hubverse project has expressed a desire to not manage
any more workflows.

If there's a way to include a generalizable workflow in the dashboard template (i.e., admins don't have to make changes to it) or if there's a way to share the hub-specific version of the repo, that doesn't seem terrible.

In any case, I'd like to make sure we're making a good tradeoff between user desire for "no more workflows" and the added complexity introduced by introducing another service into the dashboard update process.

2024-12-18 20:55 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> + - A set of GitHub workflows only
```suggestion
#### A set of GitHub workflows copied to individual hub dashboard repos

Similar to current Hubverse-developed GitHub actions. Hub admins copy workflow
and update as needed. Configured to run on a cron schedule and manually as
needed.

- PRO: Doesn't require a security token that has write access to a control
room-type repository
- PRO: Doesn't require API/web service
- CON: Increased maintenance burden for hub admins
- CON: Potential increased support burden for hub devs
- NEUTRAL: Does not use GitHub app

#### Centralized workflows invoked by individual hub repos via PAT

Hub dashboard repos have a small boilerplate workflow that invokes the control
room workflows that perform dashboard tasks. Hub admins generate and maintain a
personal GitHub Personal Access token with write access to the control room repo.

- PRO: Centralized workflows are easier for hub devs to maintain
- PRO: Doesn't require API/web service
- PRO: Less workflow boilerplate for hub admins (but not zero)
- CON: Decentralized secrets management
- NEUTRAL: Does not use GitHub app

#### Centralized workflows invoked by individual hub repos via GitHub App token

Hub dashboard repos have a small boilerplate workflow that invokes the control
room workflows that perform dashboard tasks. Hub admins store the GitHub app
token as repo secret and use it when invoking the control room workflows.

- PRO: Centralized workflows are easier for hub devs to maintain
- PRO: Doesn't require API/web service
- PRO: Less workflow boilerplate for hub admins (but not zero)
- CON: Sharing the GitHub App token
- NEUTRAL: Uses a GitHub app

#### Centralized workflows automatically copied to individual dashboard repos

Dashboard workflows are maintained in the control room app, but some kind of
CI/build process automatically adds (or updates) them to individual hub
dashboard repos.

- PRO: Benefits of centralized repo + sidesteps need for hub dashboard repos
to have write access to control room app
- PRO: Doesn't require API/web service
- CON: In practice, keeping things synchronized between individual repos and
a central repo is difficult
- NEUTRAL: Does not use GitHub app

#### Secrets vault

Hub dashboard repos have a small boilerplate workflow that invokes the control
room workflows that perform dashboard tasks. The boilerplate workflow retrieves
the GitHub app secret from a secrets value (e.g., Hashicorp Vault or AWS
Secrets Manager).

- PRO: Centralized workflows are easier for hub devs to maintain
- PRO: Doesn't require API/web service
- PRO: Less workflow boilerplate for hub admins (but not zero)
- CON: It replaces the API/web service moving part with a different moving part
(albeit one that's similar to the existing onboarding process for cloud-based
hubs)
- NEUTRAL: Uses a GitHub app
```

2024-12-18 21:16 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> + - We will host the App's webhook code on a free service like glitch.io
Repeating my question from a Zoom call: our synchronous discussion was helpful for understanding how the webhook/API component of this decision improves usability for hub admins while maintaining a good security posture.

That said, a lot of us have pushed back against running and maintaining an API/web service, as it adds a non-trivial moving part to our setup.

As expected, everyone has their own .02 about where to land on the hub admin usability <--> hub dev maintainability spectrum. I'm wondering how much (if at all) the choice of host/language for the API impacts that perspective.

2024-12-18 21:29 UTC, bsweger commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +- CON: It replaces the API/web service moving part with a different moving part
A way this could work ... GitHub actions in the hub dashboard repos could authenticate to a vault app via its GitHub OIDC provider and get the GitHub app token ([HasiCorp Vault](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-hashicorp-vault) or [AWS](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) for example). OIDC is how the [AWS Upload action](https://github.com/hubverse-org/hubverse-actions/blob/main/hubverse-aws-upload/hubverse-aws-upload.yaml#L38) is able to push data to a hub's S3 bucket.

As with getting hubs onto the Hubverse-hosted AWS cloud, there would need to be an onboarding process for hub dashboards. Essentially, we'd have to make sure each individual hubverse dashboard repo is allowed to access the vault, either manually or via infrastructure as code (the [relevant bit for AWS cloud onboarding](https://github.com/hubverse-org/hubverse-infrastructure/blob/main/src/hubverse_infrastructure/hubs/iam.py#L11))

This _might_ require less ongoing maintenance than running an API, but it's still not trivial.

2024-12-18 22:10 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +   - **Not chosen because of maintenance burden for hubverse admins** (see
> If there's a way to include a generalizable workflow in the dashboard template (i.e., admins don't have to make changes to it).

As soon as a workflow is introduced, it's out of our control. We can do our darnedest to make sure admins don't have to make changes to it, but I have yet to ever find an example where that's the case.

> if there's a way to share the hub-specific version of the repo, that doesn't seem terrible.

I'm not sure I understand this. Can you elaborate?

2024-12-18 22:29 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> + - We will host the App's webhook code on a free service like glitch.io
> I'm wondering how much (if at all) the choice of host/language for the API impacts that perspective.

I suspect that a language for the API that is more aligned with the lab languages would make the app option more appealing (depending on how robust the abstraction is). Most of the challenge with the app code is dealing with GitHub's API: https://github.com/hubverse-org/hub-dashboard-control-room/blob/60fc0660a96f054123d702c7dbe4b2108545f73f/app/index.js#L4-L24

2024-12-18 22:35 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +# 2024-12-13 Orchestration of the Dashboard Build Process
Agreed with @bsweger, the general workflow management problem is out of scope here.

2024-12-18 22:46 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +a central repo is difficult
To expand a bit on this, it is difficult not because the process involved is challenging per-se, but it requires folks to be careful about the permissions of the tokens they use. In order to update workflow files, a GitHub token needs both the `contents: write` and `workflows: write` contexts.

I've done this before and it's stressful: https://github.com/carpentries/sandpaper/tree/main/inst/workflows#updates

2024-12-18 22:56 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +- CON: It replaces the API/web service moving part with a different moving part
Four things:

1. there would be no need for an app here because the secret is a PAT for the control-room repository that's needed to send a repository dispatch event, not an app secret. 
2. we lose control of the PAT as soon as it leaves the vault.
3. every solution that involves sharing a PAT or some sort of secret is effectively re-inventing one aspect of what an app is doing in a much less secure way. 
4. there's the ongoing maintenance of rotation of the token for security.

2024-12-19 13:27 UTC, nickreich commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +- CON: It replaces the API/web service moving part with a different moving part
It seems like some of the conversation here is hinging on security concerns. It's not fully clear to me what the concerns are, or what the implications would be if the token was either misused or fell into "bad actor" hands. What could get borked? What is a "worst case scenario" here?

2024-12-19 14:33 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +#### Centralized workflows invoked by individual hub repos via PAT
This option comes closest to what I understood as the option we chose yesterday to focus on in a next phase of exploration.  But I'm confused by the part of this title that says "invoked by individual hub repos via PAT".  I was thinking there was a way this could be done without requiring individual hub admins to maintain a PAT for calling the re-usable workflows.  This would involve placing a reduced version of [the build.yaml file[(==](https://github.com/hubverse-org/hub-dashboard-control-room/blob/main/.github/workflows/build.yaml) in each hub dashboard repo, calling the centrally-maintained re-usable workflow(s).  I thought that would not require a PAT, but am I missing something?

2024-12-24 19:41 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +- CON: It replaces the API/web service moving part with a different moving part
> What could get borked? What is a "worst case scenario" here?

This token would be specific for the control-room repository. It would allow anyone with access to that token to insert _any code they want_ into the this central repository. They could insert code that would insert malicious javascript in the dashboard websites so that it either redirects to another page (either adware, scam, or other malicious site), adds a popup asking for credentials, or any other number of attacks that can be pulled off with javascript.

2024-12-24 19:51 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +personal GitHub Personal Access token with write access to the control room repo.
This is incorrect. It's not possible for hub admins to generate a PAT to the control room repo. Only administrators for the hubverse and/or owners of that control room repository can generate this PAT.

2024-12-24 19:51 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +#### Centralized workflows invoked by individual hub repos via PAT
No. This was the one I was vehemently against because of the PAT. The one above this is what we asked me to create an example of (I walked you through this yesterday https://github.com/zkamvar/hub-dashboard-workflow/blob/23af1fcc2c1631f3be4afcba0746401971a40a53/.github/workflows/rebuild-data.yaml)

This particular workflow was one that was proposed where the workflow would send a `repository_dispatch` event to the central GitHub repository. The problem with this is that it requires a PAT that can only be generated by us, which provides a security risk.

2024-12-24 19:52 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +personal GitHub Personal Access token with write access to the control room repo.
```suggestion
room workflows that perform dashboard tasks. Hub admins are provided a
personal GitHub Personal Access token with write access to the control room repo. Hubverse organization owners are required to maintain and rotate the token.
```

2024-12-24 20:27 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +#### Centralized workflows invoked by individual hub repos via PAT
Thanks for the clarification; that makes sense.  I was confused because I understood the one above as indicating that the "full" workflows would need to be copied to each repo, which is bad.  I'll resolve this conversation and make a suggestion above attempting to clarify.

2024-12-24 20:31 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +needed.
I understood the original language here as saying that the full workflow files would be copied over to the individual hub dashboard repos.  This suggestion revises the text to talk about reusable workflows.

```suggestion
#### A set of GitHub workflows copied to individual hub dashboard repos calling centrally-maintained reusable workflows

Similar to current Hubverse-developed GitHub actions, but putting most of
the heavy lifting in centrally-maintained reusable workflows. Hub admins copy
a (relatively small) workflow to their dashboard repo and update it as needed.
Configured to run on a cron schedule and manually as needed.
```

2024-12-24 21:58 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +needed.
I believe this is the correct interpretation. It is not to say that we did not consider copying over full workflows (instead of reusable workflows), but this is a more accurate representation.

2025-01-09 17:05 UTC, elray1 commented
@zkamvar is this ready for formal review?

2025-01-09 17:09 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +
Adding this to reflect where we landed on this.  We currently have both the app described in the immediately preceding points as well as the idea in the new point here.
```suggestion
- We will also build out a method in which each hub dashboard repo has relatively-lightweight workflows that call centrally-maintained reusable workflows

```

2025-01-09 17:09 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +a central repo is difficult
```suggestion
- CON: In practice, keeping things synchronized between individual repos and
a central repo is difficult because it requires careful attention to the permissions of GitHub tokens.
```

2025-01-09 17:12 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +
```suggestion
- Provide a solution that is secure. For instance, a solution without proper attention to security could allow bad actors to insert code that would insert malicious javascript in the dashboard websites.

```

2025-01-09 17:13 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +a central repo is difficult
added a suggested comment below to get the reason for this difficulty into the document

2025-01-09 17:13 UTC, elray1 commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +- CON: It replaces the API/web service moving part with a different moving part
added a suggestion for a new point in the "Aims" section clarifying the importance of security

2025-01-09 18:14 UTC, nickreich commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +The admins of at least one hubverse project has expressed a desire to not manage
has --> have

2025-01-09 18:16 UTC, nickreich commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +   main components
```suggestion
 - define a method for generating a hubverse dashboard website using all or a subset of the three
   main components
```

2025-01-09 18:16 UTC, nickreich commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +The admins of at least one hubverse project has expressed a desire to not manage
```suggestion
The admins of at least one hubverse project have expressed a desire to not manage
```

2025-01-09 18:19 UTC, nickreich commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +
I might suggest saying something explicit like a final decision about whether or not to pick one of the App v. centrally maintained workflows has not be made yet.

2025-01-09 18:29 UTC, nickreich requested changes
I (finally) had a chance to review this PR. I think it looks really good. I have one requested change before bestowing approval on it. 

My sense was that in our pre-holiday conversations about this we ended up in a place where we said we would in the short term support two approaches to dashboard orchestration:
1. a GitHub App (as Zhian had already built)
2. centrally managed workflows (I think this is currently listed as the first item under "other options considered", and that Zhian has build a version of this as well, but that it's not in use yet since it was built after the other hubs were stood up)

To me, this part of the conversations/decisions is not reflected currently in this proposal. My suggestion is to make this explicit (I put in a comment to this effect on one of @elray1 's suggested changes) and to move the centrally managed github workflow option out of "Other options considered" so it's more clear that his has been chosen as a one of two "finalist" approaches.

2025-01-10 14:42 UTC, zkamvar commented on decisions/2024-12-13-rfc-hub-dashboard-orchestration.md
> +
@nickreich, I agree with this and I will add the context.

2025-01-10 14:44 UTC, zkamvar commented
> is this ready for formal review? If so, I believe that we need to take it out of draft status.

It was dependent on #3 and the consequences were still pending, so it's still draft. I will take it out of draft today.

2025-01-10 21:20 UTC, nickreich approved these changes
Thanks for the revisions! LGTM.

2025-01-14 16:58 UTC, merged